FROM nodered/node-red

COPY ./Simulators/NodeRed/data/package.json /data/package.json

RUN ["npm", "install", "node-red-contrib-modbus"]
RUN ["npm", "install", "node-red-contrib-opcua"]
RUN ["npm", "install", "node-red-contrib-opcua-server"]
